"""Create suppliers, products, price_history tables

Revision ID: 34ac10e8f4fc
Revises: 
Create Date: 2026-07-13 05:58:25.472032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ac10e8f4fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('csv_available', sa.Boolean(), nullable=False),
    sa.Column('xml_available', sa.Boolean(), nullable=False),
    sa.Column('affiliate_feed', sa.Boolean(), nullable=False),
    sa.Column('manual_import', sa.Boolean(), nullable=False),
    sa.Column('minimum_order', sa.String(length=100), nullable=True),
    sa.Column('shipping_notes', sa.Text(), nullable=True),
    sa.Column('marketplace_permissions', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', name='verificationstatus'), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('supplier_link', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('estimated_sell_price', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('packaging_cost', sa.Float(), nullable=True),
    sa.Column('returns_allowance', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('break_even', sa.Float(), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('demand', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.Enum('BUY_NOW', 'TEST_BUY', 'WATCH', 'SKIP', name='verdict'), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('watchlist', sa.Boolean(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_ean'), 'products', ['ean'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('VERIFIED', 'IMPORTED', 'ESTIMATED', 'MISSING', name='datasource'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_ean'), table_name='products')
    op.drop_table('products')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
