from sqlalchemy import Boolean, Enum, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.session import Base
from app.database.models.mixins import TimestampMixin
from app.database.models.enums import AlertChannel


class Alert(Base, TimestampMixin):
    """
    Generated by the Alert Agent when a product satisfies a user-defined
    threshold. Alerts are recorded here regardless of which channel they
    were sent through, so the dashboard has a single source of truth.
    """

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True)

    product_id: Mapped[int | None] = mapped_column(ForeignKey("products.id"), index=True)
    product: Mapped["Product"] = relationship()

    channel: Mapped[AlertChannel] = mapped_column(Enum(AlertChannel), default=AlertChannel.DASHBOARD)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)

    is_read: Mapped[bool] = mapped_column(Boolean, default=False)
    delivered: Mapped[bool] = mapped_column(Boolean, default=False)
    delivery_error: Mapped[str | None] = mapped_column(String(500))

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Alert id={self.id} title={self.title!r}>"
